// == ES PLUS FEATURE CUSTOMIZATION FILE ==
// This file is used for configuring which features (modes, functions, etc.) will be
// included in the final ROM.

// To add/remove features, modify the number after the equals sign for the corresponding setting.
// 1 is true, 0 is false. Other values may cause instability.

// NOTE:
// - This file does not allow you to change the MODE and SETUP menu options,
//   as well as keyboard layouts and tokens.
//   + To modify the menus and keyboard layouts, edit unk4.c.
//   + To modify tokens, edit generals.asm.

// For default ROM settings and version info configuration, see config.asm.

// ==================================================================================

// Build real ROMs. Set to 0 to build emulator ROMs.
REAL=1
