#include "../generals.h"

extern const char num_1[];
extern const char num_256[];

char num_solve(char **a, char *b);
char f_10C1E(char *num);
char f_10C2C(char *num);
void f_10CC2(num_struct *nts);
void f_10DA6(num_struct *nts);
void f_10DCA(num_struct *nts);
void num_to_str_error(char *num);
char select_result_format(char fmt1, char fmt2);
void f_10E5C(char a);
char *concat_result_template(char order, char *string);
void f_10EF8(void);
void f_10F52(char a);
void f_10F76(char a);
void f_10F92(void);
void f_10FA2(void);
void table_prompt_print(char row);
void disable_ins(void);
void update_cursor_char(void);
char *get_result_str_ptr(void);
char *concat_mathi_l(char *input);
char *concat_mathi_r(char *input);
char *concat_mathi_rl(char *input);
char *concat_mathi_rend(char *input);
char *concat_mathi_frac_startl(char *input);
char *concat_10pow(char *input);
char *concat_plus(char *input);
char *concat_negative(char *input);
char *concat_argsep(char *input);
char get_disp_setting_noradical(void);
void set_default_settings(void);
char f_112EA(void);
char get_disp_setting_rdec(void);
char f_131E8(void);
char f_131EE(char *num);
char num_parse_verif(char **input, char *numout);
char f_131EC(void);
char f_143EA(char *input);
char get_const_token(char num);
char get_conv_token(char num);
void num_to_str_base_n(char *a, char *b);
char f_144F4(char a);
char f_14516(char);
char f_14532(char a);
void num_to_str_std_lineo(char *num);
char f_149D8(char *a);
void f_1547E(char a, char b);
void f_15486(char *num);
void num_eval__(void);
char num_parse(char **input, char *numout);
char f_15DE8(void);
void f_15EE4(void);
void reset(void);
void f_16C54(char *num);
void f_16CF0(void);
void f_16E44(char *a, char *b);
void f_1A3FC(void);
void f_1A410(void);
void f_1A424(char *num, char *num2);
void f_1A438(char *a, char *b);
void f_1A44C(void);
void f_1A460(char *a, char *b);
void num_abs(char *num);
void num_unk_1_1__(char *a, char *b);
void num_add_1(void);
void f_1AC6A(char *num);
void f_1AC7E(char *num);
void f_1AC92(char *num);
char f_1ADB6(char *num);
void f_1AE06(void);
char cmplx_abs(char *num);
void f_1AFB8(char *num);
void f_1AFC8(void);
char f_1AFD8(char *num, char b);
char num_invalid__(char *num);
char num_cmp(char *num1, char *num2);
void f_1B0DC(void);
char get_numtype(char *num);
char num_fromdigit(char *dest, char digit);
void set_num_0(char *num, char result_fmt);
void num_negate(void);
void f_1B208(char *num);
void f_1B238(char *num);
char get_num_err_type(char *num);
void num_mulxp__(char *num, int exp);
int num_get_exp(char *num);
void f_1B378(char *num);
void num_trunc__(char *num);
void num_frombyte(char *num, char byte);
char num_to_byte(char *num);
void num_cpy_im(char *dest, char *src);
void num_cpy(char *dest, char *src);
void f_1B4D0(void);
char invalid_var(char *a);
