#include <string.h>

extern const char base_n_submodes[];
extern const char vars_list[];
extern const char s_table_x[];
extern const char s_table_y[];
extern const char s_table_freq[];
extern const char s_table_fx[];
extern const char s_blank_line[];
extern const char contrast_screen[];
extern const char const_input_template[];
extern const char const_screen[];
extern const char conv_screen[];
extern const char menu_clr[];
extern const char s_clr_setup[];
extern const char s_clr_mem[];
extern const char s_reset_all[];
extern const char s_clr_done_all[];
extern const char s_prompt_yes[];
extern const char s_prompt_cancel[];
extern const char s_clr_done[];
extern const char s_clr_prompt_ac[];
extern const char menu_matrix_table[];
extern const char menu_matrix[];
extern const char menu_matrix_data[];
extern const char menu_matrix_dim0[];
extern const char menu_matrix_dim1[];
extern const char menu_vector_table[];
extern const char menu_vector[];
extern const char menu_vector_data[];
extern const char menu_vector_dim[];
extern const char menu_cmplx[];
extern const char menu_base_n_0[];
extern const char menu_base_n_1[];
extern const char menu_drg[];
extern const char menu_hyp[];
extern const char menu_stat_data_edit[];
extern const char menu_stat_1var_sum[];
extern const char menu_stat_2var_sum[];
extern const char menu_stat_1var_var[];
extern const char menu_stat_2var_var[];
extern const char menu_stat_1var_minmax[];
extern const char menu_stat_2var_minmax[];
extern const char menu_stat_distr[];
extern const char menu_stat_reg[];
extern const char menu_stat_reg_quad[];
extern const char menu_ratio[];
extern const char menu_verify[];
extern const char menu_ineq[];
extern const char menu_ineq_poly2[];
extern const char menu_ineq_poly3[];
extern const char menu_setup_stat_freq[];
extern const char menu_setup_rdec[];
extern const char menu_setup_cmplx_result[];
extern const char menu_setup_decimal_mark[];
extern const char menu_setup_decimalo[];
extern const char s_prompt_solve[];
extern const char s_table_prompt_start[];
extern const char s_table_prompt_end[];
extern const char s_table_prompt_step[];
extern const char s_ratio_optn_c[];
extern const char s_ratio_optn_d[];
extern const char s_verif_result_false[];
extern const char s_verif_result_true[];
extern const char s_ineq_allreal[];
extern const char s_ineq_nosolution[];

extern char f_02676(char a);
extern char get_mathi_draw_idx(char a);
extern int smart_strlen(const char *str);
extern char *smart_strcpy(char *dest, char *src);
extern char *smart_strcat(char *dest, char *src);
extern char init_num_struct(char *num, num_struct *nts);
extern char num_exp_to_str(num_struct *nts, char *out);
extern char f_0285C(num_struct *a, char *b);
extern void f_02986(char *a, char *b, char c);
extern char get_result_disp_fmt(void);
extern char get_result_store_fmt(void);
extern char set_result_store2disp(char fmt);
extern void set_result_store_fmt(char fmt);
extern char set_result_fmt(char fmt);
extern char result_str_print(char *result, char lower);
extern void basen_base_print(void);
extern void f_02B3E(char *a, char b);
extern char get_token(char id, char *dest);
extern char get_token_length(char id);
extern void print_continue_prompt(void);
extern void print_input_area(void);
extern void num_output_print(char *a);
extern char f_02C76(void);
extern char f_02CB6(void);
extern char buffer_clear_lastnline(char n);
extern void buffer_clear(void);
extern void draw_line_vert(char x, char y0, char y1, char flags);
extern void draw_line(char x0, char y0, char x1, char y1);
extern void line_print(char x, char y, char *str);
extern void char_print(char x, char y, char chr);
extern void plot_pixel(signed char x, signed char y);
extern char get_screen_addr(char x, char y, int *addr);
extern void setup_status_bar(void);
extern void f_032A4(char a, char b, char y, char x, char *e);
extern void print_4lines_4str(char *a, char *b, char *c, char *d);
extern char print_4lines_head(char *head, char *content);
extern char print_4lines(char *string);
extern void set_up_arrow(void);
extern void set_down_arrow(void);
extern char pd_value(void);
extern void print_error(char idx);
extern void f_03558(void);
extern char is_char_keycode(char keycode);
extern char is_format_keycode(char keycode);
extern char is_ac_keycode(char keycode);
extern char f_03660(void);
extern char f_03664(void);
extern char is_mov_keycode(char keycode);
extern char is_mov_y_keycode(char keycode);
extern char is_mov_x_keycode(char keycode);
extern char f_036B8(void);
extern char filter_chars_stat_mat_vct(char keycode);
extern char filter_chars(char keycode);
extern char filter_chars_table(char keycode);
extern char filter_chars_cmplx(char keycode);
extern char f_03714(char keycode);
extern char need_reset(void);
extern char f_042AA(char **a);
extern int f_043AC(char a, char b, char c);
extern void f_043CE(char a, char b, char **c);
extern char get_num_stat_table_cols(void);
extern void f_0448A(char *a, char *b);
extern void clear_result(void);
extern void memzero(void *s, size_t n);
extern void	f_044B6(void);
extern void	f_044CE(void);
extern void	f_044D2(void);
extern void	set_keycode(char keycode);
extern void set_char_keycode(char keycode);
extern void l_var(char var, char *num);
extern void st_var(char var, char *num);
extern size_t get_remaining_stack_space(void);
extern void reset_magic_string(void);
extern void shutdown(void);
extern void delay(int ticks);
extern void waitkey(void);
extern char get_IRQ0(void);
extern char f_046AE(void);
extern void	f_046C0(void);
extern void f_046C4(void);
extern char f_046CC(void);
extern char f_046D4(void);
extern void set_contrast_sfr(char val);
extern void set_scr_normal(void);
extern void f_04796(void);
extern void set_disp_indicator(char enable);
extern void set_all_kimask(void);
extern void set_contrast2_0(void);
extern void clr_all_kimask(void);
extern void set_all_ko(void);
extern void clr_all_ko(void);
extern char is_key_pressed(void);
