char is_dms_num(char *num);
void set_default_result_fmt(void);
void f_085D2(void);
char num_to_str(char *num, char *out, char c);
void f_08764(char *a, char *b);
char f_087A2(void);
char is_mathi(void);
char is_matho(void);
int max(int a, int b);
char lerp16(unsigned int a, unsigned int b, char c, char d, unsigned int e);
char lerp8(char a, char b, char c, char d, char e);
int f_088AA(void);
char *concat_angle(char *input);
char is_sign_char(char tok);
char is_pow_char(char *a);
char f_088FE(char *a);
char is_ins_mode(void);
void concat_num_str(char *out, char *num);
void concat_sqrt(char *out, char *num);
char f_0897C(void);
char f_0898C(void);
char get_font_width(void);
void f_089AC(mathi_bbox *a, mathi_bbox b);
char f_08A0A(char a);
char f_08A2A(char a);
char f_08A48(char *a);
char f_08A66(char *a, char *b);
void mathi_set_draw_mode(char dmode);
char f_08ABA(char a);
char begin_small_font(void);
char is_table_func_input(void);
