#include <string.h>
#include "consts.h"
#include "generals.h"

char f_09962(char no_keyfunc);
char f_09BDC(char a);
char f_09D54(char tmode);
char f_09D84(void);
char display_menu(char *val, char *head);
char display_token_menu(char m, char menu_idx);
char f_0A050(char a);
void f_0A0BC(void);
char f_0A564(void);
char f_0A57A(void);
void f_0A594(char a);
void f_0A5E4(void);
void f_0A6DA(void);
void f_0A782(void);
void f_0A7FA(void);
void f_0A936(char a);
void f_0A93A(char a);
void f_0A978(void);
void f_0AA7C(void);
void f_0AB44(void);
void f_0AB6A(void);
char *f_0ABA8(char a, char b, char c);
void f_0ABDE(void);
void f_0ABFC(void);
void f_0AC28(void);
void f_0AC36(void);
void f_0AC44(void);
char f_0AD08(char a);
void setup_stat(void);
void table_home(void);
void f_0AF0A(void);
void f_0AF16(void);
char f_0AF30(char a, char b, char *num);
void reset_all(void);
void clear_setup(void);
void clear_mem(void);
void clear_input_area(void);
void clear_cache_area(void);
void f_0B05A(void);
void getscancode(int *sc);
char check_key_kio(scancode *kio);
char get_key_kio(scancode *kio);
char check_key_kio2(scancode *kio);
char f_0B3EC(void);
char scancode_to_int(scancode *a, char *keycodes);
char getkeycode(char a);
char f_0B588(void);
void set_modifiers(char keycode);
char is_modifier_keycode(char keycode);
char prompt_yes_no(void);
void wait_shift(void);
char f_0B6B6(void);
char is_eqn_result(void);
char diag_initloop(void);
void f_0B8B8(char a);
void f_0C0D0(void);
